#!/usr/bin/env python3
"""Generate the stitch charts the stocking and advent patterns reference: A-Z letters and 1-24.

Hand-typed charts are how a pattern gets a 1-star review: one row off and every letter after it is
wrong, and nobody spots it in proof. These come out of the same monospace font Etsy's buyers' PDFs
will be read in, rendered and thresholded, then asserted to be a uniform grid. Also writes a PNG
contact sheet so the charts can be looked at, not just trusted.

Usage: python3 make_charts.py            # writes patterns/charts/
"""
import os
from PIL import Image, ImageDraw, ImageFont

CELLS_W, CELLS_H = 8, 10          # chart box per glyph: 7 wide, 9 tall, 1 stitch per cell
PX = 34                          # render size before downsample
FD = "/usr/share/fonts/truetype/dejavu"
OUT = "patterns/charts"


def grid(ch):
    """Render one glyph into a CELLS_W x CELLS_H mosaic: crop to the glyph, scale to fit the chart
    box without stretching, average the ink coverage in each cell, then threshold. The aspect rule
    is the whole trick - forcing every letter into 7x9 turns an A into a blob and an I into a slab."""
    img = Image.new("L", (160, 160), 0)
    d = ImageDraw.Draw(img)
    d.text((40, 40), ch, font=ImageFont.truetype(os.path.join(FD, "DejaVuSans-Bold.ttf"), 72), fill=255)
    box = img.getbbox()
    if not box:
        raise SystemExit(f"nothing rendered for {ch!r}")
    g = img.crop(box)
    w, h = g.size
    if w / h > CELLS_W / CELLS_H:
        gw, gh = CELLS_W, max(3, round(CELLS_W * h / w))
    else:
        gh, gw = CELLS_H, max(2, round(CELLS_H * w / h))
    g = g.resize((gw, gh), Image.BOX).load()
    out = [["."] * CELLS_W for _ in range(CELLS_H)]
    x0, y0 = (CELLS_W - gw) // 2, (CELLS_H - gh) // 2
    ink = 0
    for y in range(gh):
        for x in range(gw):
            if g[x, y] > 88:                      # ~35% of the cell filled = a stitch
                out[y0 + y][x0 + x] = "#"
                ink += 1
    if ink < 8:
        raise SystemExit(f"{ch!r}: only {ink} cells filled - chart would be unreadable")
    return [c for row in out for c in row]


def join(grids, gap=1):
    """Combine several glyph grids horizontally into one chart (for 12, 24, ...)."""
    w = sum(CELLS_W for _ in grids) + gap * (len(grids) - 1)
    out = [["."] * w for _ in range(CELLS_H)]
    x = 0
    for gr in grids:
        for y in range(CELLS_H):
            for c in range(CELLS_W):
                out[y][x + c] = gr[y * CELLS_W + c]
        x += CELLS_W + gap
    return ["".join(r) for r in out]


def md_table(rows):
    head = "| " + " | ".join(f"{i+1}" for i in range(len(rows[0]))) + " |"
    sep = "|" + "---|" * len(rows[0])
    body = "\n".join("| " + " | ".join(f"`{c}`" for c in r) + " |" for r in rows)
    return f"{head}\n{sep}\n{body}"


def main():
    os.makedirs(OUT, exist_ok=True)
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    lg = {c: grid(c) for c in letters}
    for c, g in lg.items():
        assert len(g) == CELLS_W * CELLS_H, f"{c}: grid is {len(g)} cells"
        assert "#" in g, f"{c}: empty"
    dg = {c: grid(c) for c in "0123456789"}
    nums = {str(i): join([dg[ch] for ch in str(i)]) for i in range(1, 25)}

    with open(f"{OUT}/AZ-name-chart.md", "w") as fh:
        fh.write(f"# A-Z name chart\n\nGenerated by `make_charts.py` - one square = one stitch, "
                 f"{CELLS_W} wide x {CELLS_H} tall, worked across the stocking leg.\nDo not hand-edit "
                 f"this file: change the generator and re-run, then regenerate the preview.\n\n")
        for c in letters:
            rows = [lg[c][i * CELLS_W:(i + 1) * CELLS_W] for i in range(CELLS_H)]
            fh.write(f"## {c}\n\n{md_table(rows)}\n\n")
        fh.write("## Names that do not fit\n\nIf a name is longer than the leg is wide, work it in "
                 "two lines centred, or drop to 1 square = 2 stitches with a 2 mm yarn - the chart "
                 "does not change, only the scale note does.\n")

    with open(f"{OUT}/numbers-1-24.md", "w") as fh:
        fh.write("# Number chart 1-24\n\nGenerated by `make_charts.py` for the advent garland. "
                 "Single digits are 7 x 9; teens and up join two glyphs with a 1-cell gap.\n\n")
        for i in range(1, 25):
            fh.write(f"## Day {i}\n\n{md_table([nums[str(i)][j:j + len(nums[str(i)][0])] for j in range(0, CELLS_H * len(nums[str(i)][0]), len(nums[str(i)][0]))])}\n\n")

    def rows_of(flat, width):
        return [flat[k * width:(k + 1) * width] for k in range(CELLS_H)]

    labels = list(letters)
    letter_rows = {c: rows_of(lg[c], CELLS_W) for c in labels}
    number_rows = {k: [list(r) for r in nums[k]] for k in sorted(nums, key=int)}
    sampler(letter_rows, f"{OUT}/preview_alphabet_sampler.png")
    sampler(number_rows, f"{OUT}/preview_numbers.png", cols=6, cell=13)
    print(f"charts: 26 letters + 24 numbers -> {OUT}/ (5 files)")


def sampler(rows_by_label, path, cols=6, cell=22):
    """One image of every glyph at a size a human can actually read - the check a text dump cannot
    do. Also the listing image that shows the chart's quality."""
    rows_by_label = {k: (v if isinstance(v[0], str) else v) for k, v in rows_by_label.items()}
    per_h = (CELLS_H + 2) * cell
    span = max(len(r[0]) for v in rows_by_label.values() for r in [v]) * cell + 44
    w = cols * span
    h = per_h * ((len(rows_by_label) + cols - 1) // cols)
    img = Image.new("RGB", (w, h), (245, 239, 230))
    d = ImageDraw.Draw(img)
    for n, lab in enumerate(rows_by_label):
        cx = (n % cols) * span
        cy = (n // cols) * per_h
        d.text((cx + 6, cy + 2), lab, font=ImageFont.truetype(
            os.path.join(FD, "DejaVuSans-Bold.ttf"), 18), fill=(122, 114, 101))
        for j, row in enumerate(rows_by_label[lab]):
            for i, chx in enumerate(row):
                if chx == "#":
                    d.rectangle((cx + 10 + i * cell, cy + 26 + j * cell,
                                 cx + 9 + (i + 1) * cell, cy + 25 + (j + 1) * cell), fill=(31, 70, 52))
    img.save(path)


if __name__ == "__main__":
    main()
